name: second
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to build and upload (e.g. "v9.8.7")'
        required: true
      dryrun:
        description: 'Perform all the steps except uploading to the release page'
        required: true
        default: "true"  # 'choice' type requires string value
        type: choice
        options:
          - "true"  # Must be quoted string, boolean value not supported.
          - "false"


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Determine Version
      id: getversion
      run: |
        echo ${{ inputs.version }}
        echo ${{ inputs.dryrun }}